//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvc5_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement_Org
    {
        public System.Guid AnnounceId { get; set; }
        public System.DateTime PostTime { get; set; }
        public string Poster { get; set; }
        public Nullable<System.Guid> PosterId { get; set; }
        public System.Guid ReceiverOrgId { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public int Type { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> Priority { get; set; }
        public System.DateTime AnnounceTimeStart { get; set; }
        public System.DateTime AnnounceTimeEnd { get; set; }
        public string ContentType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
