//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMvc5_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid EmployeeId { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<bool> EmployeeTag1 { get; set; }
        public Nullable<bool> EmployeeTag2 { get; set; }
        public string AgentId { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public Nullable<int> Rank { get; set; }
        public string EmployeeType1 { get; set; }
        public string EmployeeType2 { get; set; }
        public string EmployeeType3 { get; set; }
        public string Language { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<double> Productivity { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> LaborRuleId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public string CertificationId { get; set; }
        public Nullable<System.DateTime> OnDutyDate { get; set; }
        public string HomePhone1 { get; set; }
        public string HomePhone2 { get; set; }
        public Nullable<bool> IsCanWorked { get; set; }
        public Nullable<System.Guid> SwapGroupId { get; set; }
        public Nullable<System.Guid> OffDuteGroupId { get; set; }
        public Nullable<System.Guid> TimeOffGroupId { get; set; }
        public Nullable<int> BiddingGroupId { get; set; }
    }
}
